[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -jar target/EsportTournament-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_HOME = "/nix/var/nix/profiles/default/lib/openjdk"
MAVEN_OPTS = "-Dmaven.compiler.release=21"
