spring:
  application:
    name: EsportTournament

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    
    url: jdbc:${DATABASE_URL:jdbc:postgresql://localhost:5432/esport}
    # username: ${DB_USERNAME:postgres}  
    # password: ${DB_PASSWORD:}  
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  security:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    show-sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      # url: ${REDIS_URL:${REDIS_PUBLIC_URL:}}
      host: ${REDISHOST}
      port: ${REDISPORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  cache:
    type: ${CACHE_TYPE:simple}

  jackson:
    time-zone: Asia/Kolkata
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: ${PORT:8080}

app:
  firebase:
    # config-path: ${FIREBASE_CONFIG_PATH:firebase-service-account.json}
    credentials: ${FIREBASE_CREDENTIALS}

  admin:
    password: ${APP_ADMIN_PASSWORD:admin123}

logging:
  level:
    root: INFO
    com.esport: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    name: ${LOG_PATH:}
    max-size: 10MB
    max-history: 30

debug: ${DEBUG:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
